### ISSUE TITLE
spatstat.univar is missing

### ISSUE THREAD

**Issue by jeroen** [r-universe/spatstat#1]
Packages in `spatstat.r-universe.dev` fail to build because:

```
  ERROR: lazy loading failed for package ‘spatstat.linnet’
  Error: package ‘spatstat.univar’ 2.0.2 was found, but >= 2.0.3 is required by ‘spatstat.linnet’
  Execution halted
```

You can probably fix this by adding this package to your [packages.json](https://github.com/spatstat/spatstat.r-universe.dev/blob/HEAD/packages.json)

**Comment by rubak** [comment]
Sorry that I didn't see this message earlier. It should be fixed now.
